### ISSUE TITLE
Add a destroy action to the Terraform plugin

### ISSUE THREAD

**Issue by jvanzyl** [walmartlabs/concord-plugins#1]
Having the ability to destroy resources with Terraform using the Concord plugin would be very useful. Our group would definitely like to use Concord for all Terraform operations.

**Comment by ibodrov** [comment]
Released in terraform-task 1.12.0, pending sync to Central
CC @mgobec

**Comment by mgobec** [comment]
Sweet. Thanks @ibodrov
